package industries.nearcore.rule.engine;

import java.lang.Number;
import java.lang.String;
import java.lang.Boolean;
import java.math.BigDecimal;
import java.lang.Double;
import java.util.*;
import java.time.*;
import industries.nearcore.rule.engine.cartDetails;
import industries.nearcore.rule.engine.cartLineDetails;
import industries.nearcore.rule.engine.loyaltyMember;

global industries.nearcore.rule.engine.ActionHelper actionHelper;


rule "UP_RS_193_Rule_NonEliglible_{0}-1"
dialect "java"
salience -2
enabled true
date-effective "2-Nov-2023"
    when
        Number(doubleValue() > 1) from accumulate ( cartLineDetails(cartLineProductId in ("{1}" , "NotUsedProduct" ) && $qty : cartLineItemQuantity != null), sum($qty) )
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == true)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}") && cartLineProductCategoryId == "Category1", discount == 0.0))
    then
        actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-1");
end



rule "UP_RS_193_Rule_NonEliglible_{0}-2"
dialect "java"
salience -2
enabled true
date-effective "2-Nov-2023"
    when
        Number(doubleValue() > 1) from accumulate ( cartLineDetails(cartLineProductId in ("{1}" , "NotUsedProduct" ) && $qty : cartLineItemQuantity != null), sum($qty) )
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == false)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
    then
         actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-2");

end



rule "UP_RS_193_Rule_NonEliglible_{0}-3"
dialect "java"
salience -3
enabled true
date-effective "2-Nov-2023"
    when
        $cartDetails2 : cartDetails(transactionAmount >= 500.0, transactionAmount <= 1000.0,
                                    currencyISOCode == "USD", discountAmount == 0.0)
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == true)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
    then
       // apply a 10% discount
       modify($cartDetails2) '{' setDiscountAmount(0.1) '}'

       actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-3");
end



rule "UP_RS_193_Rule_NonEliglible_{0}-4"
dialect "java"
salience -3
enabled true
date-effective "2-Nov-2023"
    when
        $cartDetails2 : cartDetails(transactionAmount >= 500.0 && transactionAmount <= 1000.0 && currencyISOCode == "USD")
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == false)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
    then
        actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-4");
end



rule "UP_RS_193_Rule_NonEliglible_{0}-5"
dialect "java"
salience -4
enabled true
date-effective "2-Nov-2023"
    when
        $cartLineDetails4 : cartLineDetails(cartLineProductCategoryId == "Category1", discount == 0.0)
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == true)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
        Number(doubleValue() > 1) from accumulate ( cartLineDetails(cartLineProductId in ("{1}" , "NotUsedProduct" ) && $qty : cartLineItemQuantity != null), sum($qty) )
        Number(doubleValue() > 1) from accumulate ( cartLineDetails(cartLineProductId in ("{2}" ) && $qty : cartLineItemQuantity != null), sum($qty) )
    then
       // apply a 10% discount
       modify($cartLineDetails4) '{' setDiscount(0.1) '}'

       actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-5");
end



rule "UP_RS_193_Rule_NonEliglible_{0}-6"
dialect "java"
salience -4
enabled true
date-effective "2-Nov-2023"
    when
        $cartLineDetails4 : cartLineDetails(cartLineProductCategoryId == "Category1", discount == 0.0)
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == false)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
        Number(doubleValue() > 1) from accumulate ( cartLineDetails(cartLineProductId in ("{1}" , "NotUsedProduct" ) && $qty : cartLineItemQuantity != null), sum($qty) )
        Number(doubleValue() > 1) from accumulate ( cartLineDetails(cartLineProductId in ("{2}" ) && $qty : cartLineItemQuantity != null), sum($qty) )
    then
       // apply a 10% discount
       modify($cartLineDetails4) '{' setDiscount(0.1) '}'

        actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-6");
end



rule "UP_RS_193_Rule_NonEliglible_{0}-7"
dialect "java"
salience -5
enabled true
date-effective "2-Nov-2023"
    when
        $cartLineDetails2 : cartLineDetails(cartLineProductId not in ("NotInProduct"), discount == 0.0)
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == true)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
    then
       // apply a 10% discount
       modify($cartLineDetails2) '{' setDiscount(0.1) '}'

       actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-7");
end



rule "UP_RS_193_Rule_NonEliglible_{0}-8"
dialect "java"
salience -5
enabled true
date-effective "2-Nov-2023"
    when
        $cartLineDetails2 : cartLineDetails(cartLineProductId not in ("NotInProduct"), discount == 0.0)
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == false)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
    then
       // apply a 10% discount
       modify($cartLineDetails2) '{' setDiscount(0.1) '}'

       actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-8");

end






