package industries.nearcore.rule.engine;

import java.lang.Number;
import java.lang.String;
import java.lang.Boolean;
import java.math.BigDecimal;
import java.lang.Double;
import java.util.*;
import java.time.*;
import industries.nearcore.rule.engine.cartDetails;
import industries.nearcore.rule.engine.cartLineDetails;
import industries.nearcore.rule.engine.loyaltyMember;

global industries.nearcore.rule.engine.ActionHelper actionHelper;


//rule "UP_RS_193_Rule_NonEliglible_{0}-7"
//dialect "java"
//salience -5
//date-effective "2-Nov-2023"
//    when
//        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
//        not $cartLineDetails2 : cartLineDetails(cartLineProductId == ("NotInProduct"))
//        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == true)
//    then
//       actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-7");
//
//end


rule "UP_RS_193_Rule_NonEliglible_{0}-7b"
dialect "java"
salience -5
date-effective "2-Nov-2023"
    when
        $cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1")
        not $cartLineDetails2 : cartLineDetails(cartLineProductId == ("NotInProduct"))
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == true)
    then
       actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-7");

end



//rule "UP_RS_193_Rule_NonEliglible_{0}-8"
//dialect "java"
//salience -5
//date-effective "2-Nov-2023"
//    when
//        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}" ) && cartLineProductCategoryId == "Category1"))
//        not $cartLineDetails2 : cartLineDetails(cartLineProductId == ("NotInProduct"))
//        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == false)
//    then
//        actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-8");
//
//end
//


