package industries.nearcore.rule.engine;

import java.lang.Number;
import java.lang.String;
import java.lang.Boolean;
import java.math.BigDecimal;
import java.lang.Double;
import java.util.*;
import java.time.*;
import industries.nearcore.rule.engine.cartDetails;
import industries.nearcore.rule.engine.cartLineDetails;
import industries.nearcore.rule.engine.loyaltyMember;


global industries.nearcore.rule.engine.ActionHelper actionHelper;


rule "UP_RS_193_Rule_NonEliglible_{0}-1"
dialect "java"
salience -2
enabled true
date-effective "2-Nov-2023"
    when
        Number(doubleValue() > 1) from accumulate ( cartLineDetails(cartLineProductId in ("{1}" , "NotUsedProduct" ) && $qty : cartLineItemQuantity != null), sum($qty) )
        $loyaltyMember3 : loyaltyMember(isLoyaltyMember == true)
        exists($cartLineDetails1 : cartLineDetails(cartLineProductId in ("{1}") && cartLineProductCategoryId == "Category1"))
    then
        actionHelper.addAction("Executed UP_RS_193_Rule_NonEliglible_{0}-1");
end
